### ISSUE TITLE
Does not work on OPA version v0.23.0 and above.

### ISSUE THREAD

**Issue by jferrater** [jferrater/opa-data-filter-spring-boot-starter#65]
Starting OPA v0.23.0:
The ast.Array type has been redefined a struct. Previously ast.Array was a type alias for []*ast.Term. This change is backwards incompatible because slice operations can no longer be performed directly on values of type ast.Array. To accomodate, the ast.Array type now exports functions for the same operations. This change decouples callers from the underlying array implementation which opens up room for future optimizations.

The above changes in OPA breaks the compiler response deserializer.

**Comment by jferrater** [comment]
Fixed in version 0.5.1.

**Comment by zh32** [comment]
Still doesn't work. Tested with OPA version 0.23.0 and 0.49.0.
